### ISSUE TITLE
Handle `PM_ASSOC_SPLAT_NODE` when it appears in anonymous kwarg forwarding

### ISSUE THREAD

**Issue by egiurleo** [Shopify/sorbet#231]
```
def foo(**)
  bar(**)
      ^^ PM_ASSOC_SPLAT_NODE
```

Currently, the above case is not handled by our translation layer because this should be translated into a `ForwardedKwrestArg` in Sorbet's AST, which requires us to rethink the way we are handling hash translation.

**Comment by amomchilov** [comment]
Implemented in #232
